org.gradle.jvmargs=-Xmx4G

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3
loom_version=1.14-SNAPSHOT

# Fabric API
fabric_version=0.140.0+1.21.11

# Mod Properties
mod_version=0.0.1-beta69-1.21.11
maven_group=net.kyrptonaught
archives_base_name=customportalapi